// <auto-generated />
using System;
using AutoSignals.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoSignals.Migrations.AutoSignalsDb
{
    [DbContext(typeof(AutoSignalsDbContext))]
    [Migration("20260415110701_AddNeverExpires")]
    partial class AddNeverExpires
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoSignals.Models.AdminSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Key");

                    b.ToTable("AdminSettings");
                });

            modelBuilder.Entity("AutoSignals.Models.Analytics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PageName", "Date");

                    b.ToTable("Analytics");
                });

            modelBuilder.Entity("AutoSignals.Models.BinanceAssetPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(28, 8)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Type")
                        .IsUnique();

                    b.ToTable("BinanceAssetPrices");
                });

            modelBuilder.Entity("AutoSignals.Models.BinanceMarket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPrecision")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("BaseCoin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFutures")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpot")
                        .HasColumnType("bit");

                    b.Property<decimal>("MakerFeeRate")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<int>("MaxLever")
                        .HasColumnType("int");

                    b.Property<int>("MinLever")
                        .HasColumnType("int");

                    b.Property<decimal>("MinTradeUSDT")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("PricePrecision")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("QuoteCoin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TakerFeeRate")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BinanceMarkets");
                });

            modelBuilder.Entity("AutoSignals.Models.BinanceRemovedAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BinanceRemovedAssets");
                });

            modelBuilder.Entity("AutoSignals.Models.BitgetAssetPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(28, 8)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Type")
                        .IsUnique();

                    b.ToTable("BitgetAssetPrices");
                });

            modelBuilder.Entity("AutoSignals.Models.BitgetMarket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPrecision")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("BaseCoin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFutures")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpot")
                        .HasColumnType("bit");

                    b.Property<decimal>("MakerFeeRate")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<int>("MaxLever")
                        .HasColumnType("int");

                    b.Property<int>("MinLever")
                        .HasColumnType("int");

                    b.Property<decimal>("MinTradeUSDT")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("PricePrecision")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("QuoteCoin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TakerFeeRate")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Type")
                        .IsUnique();

                    b.ToTable("BitgetMarkets");
                });

            modelBuilder.Entity("AutoSignals.Models.BitgetRemovedAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BitgetRemovedAssets");
                });

            modelBuilder.Entity("AutoSignals.Models.BybitAssetPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(28, 8)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Type")
                        .IsUnique();

                    b.ToTable("BybitAssetPrices");
                });

            modelBuilder.Entity("AutoSignals.Models.BybitMarket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPrecision")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("BaseCoin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFutures")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpot")
                        .HasColumnType("bit");

                    b.Property<decimal>("MakerFeeRate")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<int>("MaxLever")
                        .HasColumnType("int");

                    b.Property<int>("MinLever")
                        .HasColumnType("int");

                    b.Property<decimal>("MinTradeUSDT")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("PricePrecision")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("QuoteCoin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TakerFeeRate")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BybitMarkets");
                });

            modelBuilder.Entity("AutoSignals.Models.BybitRemovedAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BybitRemovedAssets");
                });

            modelBuilder.Entity("AutoSignals.Models.Exchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferalClicked")
                        .HasColumnType("int");

                    b.Property<string>("ReferralBonus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exchanges");
                });

            modelBuilder.Entity("AutoSignals.Models.GeneralAssetPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(28, 8)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol");

                    b.HasIndex("Symbol", "Time");

                    b.HasIndex("Symbol", "Type")
                        .IsUnique();

                    b.ToTable("GeneralAssetPrices");
                });

            modelBuilder.Entity("AutoSignals.Models.KLineAssetPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(28, 8)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Type", "Time");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Symbol", "Type", "Time"), new[] { "Price", "Open", "High", "Low", "Close", "Volume" });

                    b.ToTable("KLineAssetPrices");
                });

            modelBuilder.Entity("AutoSignals.Models.KuCoinAssetPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(28, 8)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Type")
                        .IsUnique();

                    b.ToTable("KuCoinAssetPrices");
                });

            modelBuilder.Entity("AutoSignals.Models.KuCoinMarket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPrecision")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("BaseCoin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFutures")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpot")
                        .HasColumnType("bit");

                    b.Property<decimal>("MakerFeeRate")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<int>("MaxLever")
                        .HasColumnType("int");

                    b.Property<int>("MinLever")
                        .HasColumnType("int");

                    b.Property<decimal>("MinTradeUSDT")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("PricePrecision")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("QuoteCoin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TakerFeeRate")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KuCoinMarkets");
                });

            modelBuilder.Entity("AutoSignals.Models.KuCoinRemovedAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("KuCoinRemovedAssets");
                });

            modelBuilder.Entity("AutoSignals.Models.OkxAssetPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(28, 8)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Type")
                        .IsUnique();

                    b.ToTable("OkxAssetPrices");
                });

            modelBuilder.Entity("AutoSignals.Models.OkxMarket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPrecision")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("BaseCoin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFutures")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpot")
                        .HasColumnType("bit");

                    b.Property<decimal>("MakerFeeRate")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<int>("MaxLever")
                        .HasColumnType("int");

                    b.Property<int>("MinLever")
                        .HasColumnType("int");

                    b.Property<decimal>("MinTradeUSDT")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("PricePrecision")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("QuoteCoin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TakerFeeRate")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OkxMarkets");
                });

            modelBuilder.Entity("AutoSignals.Models.OkxRemovedAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OkxRemovedAssets");
                });

            modelBuilder.Entity("AutoSignals.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExchangeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExchangeOrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExchangeResponseJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIsolated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTest")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSyncTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Leverage")
                        .HasColumnType("float");

                    b.Property<string>("PositionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SignalId")
                        .HasColumnType("int");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("Stoploss")
                        .HasColumnType("float");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TelegramId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "SignalId", "Symbol");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AutoSignals.Models.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("AutoSignals.Models.PortfolioHolding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("AverageBuyPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("PortfolioHoldings");
                });

            modelBuilder.Entity("AutoSignals.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("ClosePrice")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Entry")
                        .HasColumnType("float");

                    b.Property<double>("EstLiquidation")
                        .HasColumnType("float");

                    b.Property<string>("ExchangeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIsolated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTest")
                        .HasColumnType("bit");

                    b.Property<int>("Leverage")
                        .HasColumnType("int");

                    b.Property<double>("ROI")
                        .HasColumnType("float");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Stoploss")
                        .HasColumnType("float");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TelegramId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Symbol", "Side", "Status");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("AutoSignals.Models.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AverageLeverage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AverageProfitPerTrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AverageWinRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastProvidedSignal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LongCount")
                        .HasColumnType("int");

                    b.Property<int?>("LongRatio")
                        .HasColumnType("int");

                    b.Property<string>("LongWinRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RRR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Risk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShortCount")
                        .HasColumnType("int");

                    b.Property<int?>("ShortRatio")
                        .HasColumnType("int");

                    b.Property<string>("ShortWinRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SignalCount")
                        .HasColumnType("int");

                    b.Property<string>("SignalsNullified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoplossPersentage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TakeProfitDistribution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TakeProfitTargets")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telegram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TpAchieved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradeStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradeTimeframes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradesPerDay")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Provider");
                });

            modelBuilder.Entity("AutoSignals.Models.ProviderParsingRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FallbackValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<string>("RegexGroupName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RegexPattern")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValidationLogic")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("ProviderParsingRules");
                });

            modelBuilder.Entity("AutoSignals.Models.ProviderSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConnectionId")
                        .HasColumnType("int");

                    b.Property<bool>("IgnorLong")
                        .HasColumnType("bit");

                    b.Property<bool>("IgnorShort")
                        .HasColumnType("bit");

                    b.Property<bool>("IgnoreStoploss")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIsolated")
                        .HasColumnType("bit");

                    b.Property<int>("Leverage")
                        .HasColumnType("int");

                    b.Property<double>("MaxTradeSizeUsd")
                        .HasColumnType("float");

                    b.Property<double>("MinTradeSizeUsd")
                        .HasColumnType("float");

                    b.Property<int>("MoonbagPercentage")
                        .HasColumnType("int");

                    b.Property<string>("MoonbagSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MoveStoploss")
                        .HasColumnType("bit");

                    b.Property<int>("MoveStoplossOn")
                        .HasColumnType("int");

                    b.Property<bool>("OverideLeverage")
                        .HasColumnType("bit");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RiskPercentage")
                        .HasColumnType("float");

                    b.Property<double>("StoplossPercentage")
                        .HasColumnType("float");

                    b.Property<bool>("Testing")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("TpCount")
                        .HasColumnType("int");

                    b.Property<string>("TpPercentages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UseMoonbag")
                        .HasColumnType("bit");

                    b.Property<bool>("UseStoploss")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.ToTable("ProvidersSettings");
                });

            modelBuilder.Entity("AutoSignals.Models.Signal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Entry")
                        .HasColumnType("real");

                    b.Property<int>("Leverage")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Stoploss")
                        .HasColumnType("real");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TakeProfits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Symbol");

                    b.HasIndex("Time");

                    b.HasIndex("Provider", "Time");

                    b.ToTable("Signals");
                });

            modelBuilder.Entity("AutoSignals.Models.SignalPerformance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AchievedTakeProfits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("HighPrice")
                        .HasColumnType("real");

                    b.Property<float>("LowPrice")
                        .HasColumnType("real");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotifiedTakeProfits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("ProfitLoss")
                        .HasColumnType("real");

                    b.Property<int>("SignalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TakeProfitCount")
                        .HasColumnType("int");

                    b.Property<int?>("TakeProfitsAchieved")
                        .HasColumnType("int");

                    b.Property<string>("TelegramMessageId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SignalId");

                    b.HasIndex("StartTime");

                    b.HasIndex("Status");

                    b.ToTable("SignalPerformances");
                });

            modelBuilder.Entity("AutoSignals.Models.SignalPrediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("ConfidenceScore")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeatureSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HistoricalSampleSize")
                        .HasColumnType("int");

                    b.Property<float>("MarketAlignmentScore")
                        .HasColumnType("real");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NarrativeAnalysis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ProviderAccuracyScore")
                        .HasColumnType("real");

                    b.Property<int>("ProviderSampleSize")
                        .HasColumnType("int");

                    b.Property<int>("SignalId")
                        .HasColumnType("int");

                    b.Property<float>("StoplossProbability")
                        .HasColumnType("real");

                    b.Property<string>("TpProbabilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("VolatilityFitScore")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("SignalId")
                        .IsUnique();

                    b.ToTable("SignalPredictions");
                });

            modelBuilder.Entity("AutoSignals.Models.SignalProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageParsingPrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TelegramGroupId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TelegramGroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UseAiFallback")
                        .HasColumnType("bit");

                    b.Property<bool>("UseImageParsing")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SignalProviders");
                });

            modelBuilder.Entity("AutoSignals.Models.SubscriptionEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalEventId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExternalSubscriptionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Tier")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalEventId")
                        .IsUnique()
                        .HasFilter("[ExternalEventId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("SubscriptionEvents");
                });

            modelBuilder.Entity("AutoSignals.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeaturesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAnnual")
                        .HasColumnType("bit");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Currency = "USD",
                            IsActive = true,
                            IsAnnual = false,
                            MonthlyPrice = 29.00m,
                            Name = "Pro Monthly",
                            Tier = 1
                        },
                        new
                        {
                            Id = 2,
                            Currency = "USD",
                            IsActive = true,
                            IsAnnual = true,
                            MonthlyPrice = 23.00m,
                            Name = "Pro Annual",
                            Tier = 1
                        },
                        new
                        {
                            Id = 3,
                            Currency = "USD",
                            IsActive = true,
                            IsAnnual = false,
                            MonthlyPrice = 79.00m,
                            Name = "VIP Monthly",
                            Tier = 2
                        },
                        new
                        {
                            Id = 4,
                            Currency = "USD",
                            IsActive = true,
                            IsAnnual = true,
                            MonthlyPrice = 63.00m,
                            Name = "VIP Annual",
                            Tier = 2
                        });
                });

            modelBuilder.Entity("AutoSignals.Models.UserData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiTestResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("EmailNotifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExchangeId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalSubscriptionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instagram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NeverExpires")
                        .HasColumnType("bit");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartBalance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubscriptionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubscriptionProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubscriptionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriptionStatus")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionTier")
                        .HasColumnType("int");

                    b.Property<string>("TelegramId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelegramNotifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TrialEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("X")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionStatus");

                    b.HasIndex("SubscriptionTier");

                    b.ToTable("UsersData");
                });

            modelBuilder.Entity("AutoSignals.Models.UserExchangeConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExchangeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastTestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TestResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserExchangeConnections");
                });

            modelBuilder.Entity("AutoSignals.Models.UserFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserFeedback");
                });

            modelBuilder.Entity("AutoSignals.Models.UserFeedbackImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserFeedbackId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserFeedbackId");

                    b.ToTable("UserFeedbackImages");
                });

            modelBuilder.Entity("AutoSignals.Models.UserNotificationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EmailMarketing")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailOrderExecuted")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailStopLossHit")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailTakeProfitHit")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailUpdates")
                        .HasColumnType("bit");

                    b.Property<bool>("TelegramOrderExecuted")
                        .HasColumnType("bit");

                    b.Property<bool>("TelegramStopLossHit")
                        .HasColumnType("bit");

                    b.Property<bool>("TelegramTakeProfitHit")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserNotificationSettings");
                });

            modelBuilder.Entity("AutoSignals.Models.UserVisit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BytesSent")
                        .HasColumnType("bigint");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PagePath")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress");

                    b.HasIndex("Timestamp");

                    b.ToTable("UserVisits");
                });

            modelBuilder.Entity("ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("AutoSignals.Models.PortfolioHolding", b =>
                {
                    b.HasOne("AutoSignals.Models.Portfolio", "Portfolio")
                        .WithMany("Holdings")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("AutoSignals.Models.ProviderParsingRule", b =>
                {
                    b.HasOne("AutoSignals.Models.SignalProvider", "Provider")
                        .WithMany("ParsingRules")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("AutoSignals.Models.ProviderSettings", b =>
                {
                    b.HasOne("AutoSignals.Models.UserExchangeConnection", "Connection")
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("AutoSignals.Models.UserExchangeConnection", b =>
                {
                    b.HasOne("AutoSignals.Models.Exchange", "Exchange")
                        .WithMany()
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exchange");
                });

            modelBuilder.Entity("AutoSignals.Models.UserFeedbackImage", b =>
                {
                    b.HasOne("AutoSignals.Models.UserFeedback", "UserFeedback")
                        .WithMany("Images")
                        .HasForeignKey("UserFeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserFeedback");
                });

            modelBuilder.Entity("AutoSignals.Models.Portfolio", b =>
                {
                    b.Navigation("Holdings");
                });

            modelBuilder.Entity("AutoSignals.Models.SignalProvider", b =>
                {
                    b.Navigation("ParsingRules");
                });

            modelBuilder.Entity("AutoSignals.Models.UserFeedback", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
